version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/Desktop/postgres-databases/intel-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=intel
      - POSTGRES_DB=intel_db
# ------------------------------------------------------------------------------|
# run : docker compose up -d                                                 |
# ------------------------------------------------------------------------------|
# connection string : postgresql://intel:root@localhost:5432/intel_db          |
# ------------------------------------------------------------------------------|
